### ISSUE TITLE
Protect the users map with a mutex

### ISSUE THREAD

**Issue by rwestlund** [aprogrammer8/fighting-game#4]
You have multiple goroutines accessing `users` concurrently, which could result in corruption. If you had no writers than multiple readers is okay, but with at least one writer, all writers and readers must serialize their access.  To envision this, what happens when `globalChat()` is iterating over the keys in `users` and `handleConnection()` inserts a new key at the same time?  Undefined behavior.

Check out `sync.Mutex`. It's pretty cool.  :)

**Comment by aprogrammer8** [comment]
Thanks for the advice. Done.
